# Generated by Django 4.2.1 on 2023-05-05 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolitciUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry', models.CharField(max_length=100, unique=True, verbose_name='pays')),
                ('city', models.CharField(max_length=100, unique=True, verbose_name='ville')),
                ('choice_parti', models.CharField(choices=[('UDC', 'UDC'), ('RDPC', 'RDPC'), ('MRC', 'MRC'), ('SDF', 'SDF')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_vote', models.IntegerField(default=0)),
                ('vote_choice', models.CharField(choices=[('UDC', 'UDC'), ('RDPC', 'RDPC'), ('MRC', 'MRC'), ('SDF', 'SDF')], max_length=100)),
                ('date_vote', models.DateField()),
                ('create_at', models.DateTimeField()),
                ('vote_militic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voting_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.politciuser')),
            ],
        ),
        migrations.CreateModel(
            name='MiliticUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry_militic', models.CharField(max_length=100, unique=True, verbose_name='pays')),
                ('city_militic', models.CharField(max_length=100, unique=True, verbose_name='ville')),
                ('parti_politi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.politciuser')),
                ('user_militic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
