# Generated by Django 4.2.1 on 2023-05-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_voting_voting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='parti_politi',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.politciuser'),
            preserve_default=False,
        ),
    ]
