# Generated by Django 4.2.1 on 2023-05-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_parti_politi_voting_parti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='parti',
        ),
    ]
