# Generated by Django 4.2.1 on 2023-05-05 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_voting_parti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militicuser',
            name='parti_politi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.politciuser'),
        ),
    ]
