# Generated by Django 4.2.1 on 2023-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_militicuser_parti_politi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politciuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='vote_militic',
        ),
        migrations.DeleteModel(
            name='MiliticUser',
        ),
        migrations.DeleteModel(
            name='PolitciUser',
        ),
        migrations.DeleteModel(
            name='Voting',
        ),
    ]
