# Generated by Django 4.2.1 on 2023-05-07 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_politciuser_user_remove_voting_vote_militic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contry', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_voting', models.IntegerField(default=1)),
                ('date_create', models.DateTimeField()),
                ('vote', models.ManyToManyField(to='core.mility')),
            ],
        ),
        migrations.CreateModel(
            name='PartiPolic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('choices_pati', models.CharField(choices=[('RDPC', 'RDPC'), ('MRC', 'MRC'), ('UDC', 'UDC')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mility',
            name='party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.partipolic'),
        ),
        migrations.AddField(
            model_name='mility',
            name='user_mility',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
