# Generated by Django 4.2.1 on 2023-05-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='name',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='voting',
            name='vote',
        ),
        migrations.AddField(
            model_name='voting',
            name='vote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.mility'),
            preserve_default=False,
        ),
    ]
