# Generated by Django 4.2.1 on 2023-05-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_voting_name_remove_voting_vote_voting_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='vote',
        ),
        migrations.AddField(
            model_name='voting',
            name='vote',
            field=models.ManyToManyField(to='core.mility'),
        ),
    ]
