# Generated by Django 4.2.1 on 2023-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_voting_vote_voting_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mility',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mility',
            name='contry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
