# Generated by Django 4.2.1 on 2023-05-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mility_city_alter_mility_contry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mility',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partipolic'),
        ),
    ]
