# Generated by Django 4.2.1 on 2023-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_voting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='number_voting',
            field=models.IntegerField(),
        ),
    ]
